# Generated by Django 3.1.5 on 2021-03-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Referenciales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('cod_proveedor', models.AutoField(primary_key=True, serialize=False, verbose_name='Código Proveedor')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Proveedor')),
                ('ruc', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=100)),
                ('timbrado', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Referenciales.ciudad')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['cod_proveedor'],
            },
        ),
    ]
