# Generated by Django 3.1.5 on 2021-02-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cod_proveedor',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código Proveedor'),
        ),
    ]
