# Generated by Django 3.1.5 on 2021-02-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0002_auto_20210217_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Proveedor'),
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedor',
        ),
    ]
