# Generated by Django 3.1.5 on 2021-03-12 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalllePrecioCompra',
            fields=[
                ('ultima_fecha_precio', models.DateField(primary_key=True, serialize=False, verbose_name='Fecha Detalle Precio')),
                ('precio_compra', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.producto')),
            ],
            options={
                'verbose_name': 'DetallePrecioCompra',
                'verbose_name_plural': 'DetallePrecioCompras',
                'db_table': 'detalle_precio_compra',
                'ordering': ['ultima_fecha_precio'],
            },
        ),
    ]
