# Generated by Django 3.1.5 on 2021-02-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0003_auto_20210218_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('cod_tipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo Tipo Producto')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Tipo Producto')),
            ],
            options={
                'verbose_name': 'Tipo Producto',
                'db_table': 'Tipo_Producto',
            },
        ),
    ]
