# Generated by Django 3.1.5 on 2021-03-12 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0004_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('nro_detalle', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Numero Detalle compra')),
                ('cantidad', models.IntegerField()),
                ('total_IVA', models.FloatField()),
                ('total_descuento', models.FloatField()),
                ('total_importe', models.FloatField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.producto')),
            ],
            options={
                'verbose_name': 'Detalle_compra',
                'verbose_name_plural': 'Detalle_compras',
                'db_table': 'detalle_compra',
            },
        ),
    ]
