# Generated by Django 3.1.5 on 2021-02-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0004_tipo_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_producto',
            old_name='cod_tipo',
            new_name='cod_tipo_producto',
        ),
        migrations.AlterModelTable(
            name='tipo_producto',
            table='Tipo_producto',
        ),
    ]
