# Generated by Django 3.1.5 on 2021-03-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0005_compradetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('cod_movimiento', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Movimiento')),
                ('tipo_movimiento', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimiento',
                'ordering': ['cod_movimiento'],
            },
        ),
    ]
