# Generated by Django 3.1.5 on 2021-02-22 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0005_auto_20210222_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo Producto')),
                ('nombre_producto', models.CharField(max_length=30, verbose_name='producto')),
                ('descripcion', models.CharField(max_length=30)),
                ('cant_stock', models.IntegerField()),
                ('cant_minima_stock', models.IntegerField()),
                ('estado', models.CharField(max_length=15)),
                ('cod_tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.tipo_producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Productos',
            },
        ),
    ]
