# Generated by Django 3.1.5 on 2021-02-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0006_producto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
    ]
