# Generated by Django 3.1.5 on 2021-03-12 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0006_movimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoProducto',
            fields=[
                ('fecha_movimiento_producto', models.DateField(primary_key=True, serialize=False, verbose_name='Fecha Movimiento Producto ')),
                ('cantidad_producto', models.ImageField(upload_to='')),
                ('detalle_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.compradetalle')),
                ('movimiento_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.movimiento')),
            ],
            options={
                'verbose_name': 'MovimientoProducto',
                'verbose_name_plural': 'MovimientoProductos',
                'db_table': 'movimiento_producto',
                'ordering': ['fecha_movimiento_producto'],
            },
        ),
    ]
