# Generated by Django 3.1.5 on 2021-02-22 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0007_auto_20210222_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos_Compra',
            fields=[
                ('nro_pedido_compra', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero Pedido')),
                ('fecha_pedido_compra', models.DateField(auto_now=True)),
                ('cantidad', models.IntegerField()),
                ('descripcion_pedidio', models.CharField(max_length=50, verbose_name='Pedido_compra')),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.producto')),
                ('cod_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido_compra',
                'verbose_name_plural': 'Pedidos_compras',
                'db_table': 'Pedido',
            },
        ),
    ]
