# Generated by Django 3.1.5 on 2021-02-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0008_pedidos_compra'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedidos_compra',
            table='Pedido_compra',
        ),
    ]
