# Generated by Django 3.1.5 on 2021-02-24 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0004_auto_20210218_2326'),
        ('Compra', '0009_auto_20210222_1703'),
    ]

    operations = [
    ]
