# Generated by Django 3.1.5 on 2021-02-24 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0010_merge_20210223_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos_compra',
            old_name='descripcion_pedidio',
            new_name='descripcion_pedido',
        ),
    ]
