# Generated by Django 3.1.5 on 2021-02-24 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0011_auto_20210223_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cod_tipo_producto',
            new_name='cod_tipo',
        ),
        migrations.RenameField(
            model_name='tipo_producto',
            old_name='cod_tipo_producto',
            new_name='cod_tipo',
        ),
        migrations.AlterModelTable(
            name='tipo_producto',
            table='tipo_producto',
        ),
    ]
