# Generated by Django 3.1.5 on 2021-03-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0013_auto_20210305_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('1', 'Producto'), ('2', 'Servicio')], default='1', max_length=2),
        ),
    ]
