# Generated by Django 3.1.5 on 2021-03-07 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Referenciales', '0004_empleado'),
        ('Compra', '0014_auto_20210306_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('tipoCompra', models.IntegerField(choices=[(0, 'Contado'), (1, 'Credito')])),
                ('nro_factura', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Numero Factura')),
                ('fecha_emision', models.DateField(auto_now=True)),
                ('total_IVA', models.FloatField()),
                ('total_descuento', models.FloatField()),
                ('total_importe', models.FloatField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Referenciales.empleado')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'Compra',
            },
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('nro_detalle', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Numero Detalle compra')),
                ('cantidad', models.IntegerField()),
                ('total_IVA', models.FloatField()),
                ('total_descuento', models.FloatField()),
                ('total_importe', models.FloatField()),
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Compra.compra', verbose_name='Compra Detalle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.producto')),
            ],
            options={
                'verbose_name': 'Detalle_compra',
                'verbose_name_plural': 'Detalle_compras',
                'db_table': 'Detalle_compra',
            },
        ),
        migrations.DeleteModel(
            name='Pedidos_Compra',
        ),
    ]
