# Generated by Django 3.1.5 on 2021-03-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0015_auto_20210306_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cant_minima_stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=30, unique=True, verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
