# Generated by Django 3.1.5 on 2021-03-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('cod_ciudad', models.AutoField(primary_key=True, serialize=False, verbose_name='Código Ciudad')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudad',
                'ordering': ['cod_ciudad'],
            },
        ),
    ]
