# Generated by Django 3.1.5 on 2021-02-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Referenciales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='cod_ciudad',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Código Ciudad'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Ciudad'),
        ),
        migrations.AlterModelTable(
            name='ciudad',
            table='ciudad',
        ),
    ]
