# Generated by Django 3.1.5 on 2021-03-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Referenciales', '0002_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('cod_condicion', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Condicion')),
                ('descripcion_cond', models.CharField(choices=[('0', 'Contado'), ('1', 'Credito')], default='0', max_length=2)),
                ('plazo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Condicion',
                'verbose_name_plural': 'Condiciones',
                'db_table': 'condicion',
                'ordering': ['cod_condicion'],
            },
        ),
    ]
