# Generated by Django 3.1.5 on 2021-02-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Referenciales', '0002_auto_20210217_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['cod_ciudad'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='cod_ciudad',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código Ciudad'),
        ),
    ]
