# Generated by Django 3.1.5 on 2021-03-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Referenciales', '0003_condicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('cod_tipo_doc', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Tipo Documento')),
                ('descripcion', models.CharField(max_length=30)),
                ('nro_timbrado', models.IntegerField()),
                ('fecha_inicio', models.DateField(auto_now=True)),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'TipoDocumento',
                'verbose_name_plural': 'TipoDocumentos',
                'db_table': 'tipo_documento',
                'ordering': ['cod_tipo_doc'],
            },
        ),
    ]
