# Generated by Django 3.1.5 on 2021-03-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Referenciales', '0004_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=30, unique=True, verbose_name='Ciudad'),
        ),
    ]
